spring:
  application:
    name: oauth2-service
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 8090

management:
  endpoint:
    health:
      enabled: true